spring.application.name=center-management

# JPA and Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Session timeout configuration (optional)
server.servlet.session.timeout=30m

# Database connection properties
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/center_management?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Supabase Configuration
supabase.url=${SUPABASE_URL:}
supabase.key=${SUPABASE_KEY:}

# Gmail SMTP configuration for sending emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Admin Default Configuration
admin.default.email=${ADMIN_EMAIL:admin@gmail.com}
admin.default.password=${ADMIN_PASSWORD:123456}
admin.default.fullname=${ADMIN_FULLNAME:System Admin}